# This workflow is designed to setup a golang workspace and execute the unit tests

name: golang-testing

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - run: echo "Executing on  ${{ runner.os }} due to ${{ github.event_name }}"
    - run: echo "Branch is ${{ github.ref }} executing on  ${{ runner.os }} due to ${{ github.event_name }}"

    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20.6
        cache: true

    - name: Go Tidy
      run: go mod tidy && git diff --exit-code

    - name: Go Mod
      run: go mod download

    - name: Go Mod Verify
      run: go mod verify

    - name: Install govulncheck
      run: go install golang.org/x/vuln/cmd/govulncheck@latest

    - name: Run govulncheck
      run: |
        govulncheck -test ./netflow/...
        govulncheck -test ./manager/...
        govulncheck -test ./ipexist/...
        govulncheck -test ./generators/ipgen/...
        govulncheck -test ./generators/base/...
        govulncheck -test ./generators/gravwellGenerator/...
        govulncheck -test ./filewatch/...
        govulncheck -test ./client/...
        govulncheck -test ./chancacher/...
        govulncheck -test ./timegrinder/...
        govulncheck -test ./ingest
        govulncheck -test ./ingest/entry/...
        govulncheck -test ./ingest/config/...
        govulncheck -test ./ingest/log
        govulncheck -test ./ingest/processors
        govulncheck -test ./ingest/processors/tags
        govulncheck -test ./ingest/processors/plugin
        govulncheck -test ./tools/...
        govulncheck -test ./kitctl/...
        govulncheck -test ./migrate/...
        govulncheck -test ./ingesters/s3Ingester
        govulncheck -test ./ingesters/HttpIngester
        govulncheck -test ./ingesters/pcapFileIngester
        govulncheck -test ./ingesters/collectd
        govulncheck -test ./ingesters/hackernews_ingester
        govulncheck -test ./ingesters/base
        govulncheck -test ./ingesters/massFile
        govulncheck -test ./ingesters/MSGraphIngester
        govulncheck -test ./ingesters/kafka_consumer
        govulncheck -test ./ingesters/reddit_ingester
        govulncheck -test ./ingesters/O365Ingester
        govulncheck -test ./ingesters/args
        govulncheck -test ./ingesters/version
        govulncheck -test ./ingesters/sqsIngester
        govulncheck -test ./ingesters/diskmonitor
        govulncheck -test ./ingesters/session
        govulncheck -test ./ingesters/snmp
        govulncheck -test ./ingesters/xlsxIngester
        govulncheck -test ./ingesters/multiFile
        govulncheck -test ./ingesters/Shodan
        govulncheck -test ./ingesters/reimport
        govulncheck -test ./ingesters/SimpleRelay
        govulncheck -test ./ingesters/KinesisIngester
        govulncheck -test ./ingesters/netflow
        govulncheck -test ./ingesters/AzureEventHubs
        govulncheck -test ./ingesters/utils
        govulncheck -test ./ingesters/IPMIIngester
        govulncheck -test ./ingesters/regexFile
        govulncheck -test ./ingesters/PacketFleet
        govulncheck -test ./ingesters/canbus
        govulncheck -test ./ingesters/GooglePubSubIngester
        govulncheck -test ./ingesters/fileFollow
        govulncheck -test ./ingesters/singleFile
        GOOS=windows govulncheck -test ./ingesters/winevents
        GOOS=windows govulncheck -test ./winevent/...

    - name: Install libpcap
      run: sudo apt-get install -y libpcap-dev

    - name: Test
      run: |
        go test -v ./generators/ipgen
        go test -v ./chancacher
        go test -v ./ingest
        go test -v ./ingest/entry
        go test -v ./ingest/processors
        go test -v ./ingest/processors/plugin
        go test -v ./ingest/config
        go test -v ./ingest/log
        go test -v ./timegrinder
        go test -v ./filewatch
        go test -v ./ingesters/utils
        go test -v ./ingesters/kafka_consumer
        go test -v ./ingesters/SimpleRelay
        go test -v ./ipexist
        go test -v ./netflow
        go test -v ./client/...
    
    - name: Build
      run: |
        go build -o /dev/null ./generators/gravwellGenerator
        go build -o /dev/null ./manager
        go build -o /dev/null ./migrate
        go build -o /dev/null ./tools/timetester
        go build -o /dev/null ./timegrinder/cmd
        go build -o /dev/null ./ipexist/textinput
        go build -o /dev/null ./kitctl
        go build -o /dev/null ./ingesters/GooglePubSubIngester
        go build -o /dev/null ./ingesters/massFile
        go build -o /dev/null ./ingesters/diskmonitor
        go build -o /dev/null ./ingesters/HttpIngester
        go build -o /dev/null ./ingesters/collectd
        go build -o /dev/null ./ingesters/xlsxIngester
        go build -o /dev/null ./ingesters/netflow
        go build -o /dev/null ./ingesters/version
        go build -o /dev/null ./ingesters/KinesisIngester
        go build -o /dev/null ./ingesters/reimport
        go build -o /dev/null ./ingesters/kafka_consumer
        go build -o /dev/null ./ingesters/MSGraphIngester
        go build -o /dev/null ./ingesters/IPMIIngester
        go build -o /dev/null ./ingesters/fileFollow
        go build -o /dev/null ./ingesters/canbus
        go build -o /dev/null ./ingesters/reddit_ingester
        go build -o /dev/null ./ingesters/s3Ingester
        go build -o /dev/null ./ingesters/snmp
        go build -o /dev/null ./ingesters/AzureEventHubs
        go build -o /dev/null ./ingesters/hackernews_ingester
        go build -o /dev/null ./ingesters/Shodan
        go build -o /dev/null ./ingesters/singleFile
        go build -o /dev/null ./ingesters/sqsIngester
        go build -o /dev/null ./ingesters/multiFile
        go build -o /dev/null ./ingesters/networkLog
        go build -o /dev/null ./ingesters/session
        go build -o /dev/null ./ingesters/regexFile
        go build -o /dev/null ./ingesters/pcapFileIngester
        go build -o /dev/null ./ingesters/SimpleRelay
        go build -o /dev/null ./ingesters/O365Ingester
        go build -o /dev/null ./ingesters/PacketFleet
        GOOS=windows go build -o /dev/null ./ingesters/fileFollow
        GOOS=windows go build -o /dev/null ./ingesters/winevents
        GOOS=windows go build ./generators/windowsEventGenerator

    - name: Final status
      run: echo "Status is ${{ job.status }} 🚀"
